import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header/header";
import Footer from "./_components/Footer/footer";
import { Toaster } from "./_components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta httpEquiv="Content-Security-Policy" content="upgrade-insecure-requests"></meta>
      <body className={inter.className}>
      <Header/>
      {children} 
      <Toaster />     
      <Footer/>
      </body>
    </html>
  );
}
